### PR TITLE
add YOLO

### PR DESCRIPTION
**Pull request by genekogan**
processing sketch to receive YOLO apps. currently just displays the object names and bounding boxes, but does not have the camera because of inability to share camera port with Runway.

### CODE REVIEW

**Comment by cvalenzuela** [comment]
looks great! thanks for this.

You can't send the camera via Runway, but you can have Processing running it's own camera:



I just added the [Capture](https://processing.org/reference/libraries/video/Capture.html) example from Processing!

**Comment by genekogan** [comment]
oh great! i thought it was knocking runway out from the camera though when you start it up.

**Comment by cvalenzuela** [comment]
Let me know if you want to push those changes or I can push them!

**Comment by genekogan** [comment]
go for it!

**Comment by cvalenzuela** [comment]
merged! thanks @genekogan!

**Pull request merged**
